-- Table for new

CREATE TABLE New_Application (
    id INT AUTO_INCREMENT PRIMARY KEY,
    application_type VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    site VARCHAR(100),
    city VARCHAR(100),
    office VARCHAR(100),
    delivery_site VARCHAR(100),
    appointment_date VARCHAR(50),
    appointment_time VARCHAR(50),
    firstname VARCHAR(100),
    middlename VARCHAR(100),
    lastname VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    gender VARCHAR(10),
    dob VARCHAR(10),
    under18 VARCHAR(5),
    birthplace VARCHAR(100),
    adopted VARCHAR(5),
    birth_certificate VARCHAR(5),
    nationality VARCHAR(50),
    marital_status VARCHAR(50),
    occupation VARCHAR(50),
    region VARCHAR(100),
    address_city VARCHAR(100),
    subcity VARCHAR(100),
    woreda VARCHAR(50),
    kebele VARCHAR(50),
    house_no VARCHAR(50),
    id_no VARCHAR(50),
   mother_first_name VARCHAR(50) NOT NULL,
    mother_father_name VARCHAR(50) NOT NULL,
    mother_grandfather_name VARCHAR(50) NOT NULL,
    father_first_name VARCHAR(50) NOT NULL,
    father_father_name VARCHAR(50) NOT NULL,
    father_grandfather_name VARCHAR(50) NOT NULL,
    spouse_first_name VARCHAR(50),
    spouse_father_name VARCHAR(50),
    spouse_grandfather_name VARCHAR(50),
    
    birth_certificate_front VARCHAR(255),
    birth_certificate_back VARCHAR(255),
    id_front VARCHAR(255),
    id_back VARCHAR(255),

    pageNo VARCHAR(6),
    application_no VARCHAR(100),
    registered_date VARCHAR(50),  
    -- System Fields
    application_status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE Lost_Application(
    id INT AUTO_INCREMENT PRIMARY KEY,
    application_type VARCHAR(50) NOT NULL,
    category VARCHAR(50),

    site VARCHAR(100),
    city VARCHAR(100),
    office VARCHAR(100),
    delivery_site VARCHAR(100),

    appointment_date VARCHAR(50),
    appointment_time VARCHAR(50),

    firstname VARCHAR(100),
    middlename VARCHAR(100),
    lastname VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    gender VARCHAR(10),
    dob VARCHAR(10),
    under18 VARCHAR(5),
    birthplace VARCHAR(100),
    adopted VARCHAR(5),
    birth_certificate VARCHAR(5),
    nationality VARCHAR(50),
    marital_status VARCHAR(50),
    occupation VARCHAR(50),

    region VARCHAR(100),
    address_city VARCHAR(100),
    subcity VARCHAR(100),
    woreda VARCHAR(50),
    kebele VARCHAR(50),
    house_no VARCHAR(50),
    id_no VARCHAR(50),

    mother_first_name VARCHAR(50) NOT NULL,
    mother_father_name VARCHAR(50) NOT NULL,
    mother_grandfather_name VARCHAR(50) NOT NULL,
    father_first_name VARCHAR(50) NOT NULL,
    father_father_name VARCHAR(50) NOT NULL,
    father_grandfather_name VARCHAR(50) NOT NULL,
    spouse_first_name VARCHAR(50),
    spouse_father_name VARCHAR(50),
    spouse_grandfather_name VARCHAR(50),
    -- Passport Information
    old_passport_number VARCHAR(50),
    old_issue_date VARCHAR(50),
    old_expiry_date VARCHAR(50),
    has_correction BOOLEAN DEFAULT FALSE,
    correction_type VARCHAR(50),
   -- Attachments
    old_passport_attachment VARCHAR(255),
    photo_attachment VARCHAR(255),
    id_front_attachment VARCHAR(255),
    id_back_attachment VARCHAR(255),
    police_assurance_attachment VARCHAR(255),

    pageNo VARCHAR(6),
    application_no VARCHAR(100),
    registered_date VARCHAR(50),  
    -- System Fields
    application_status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE Correction_Application(
    id INT AUTO_INCREMENT PRIMARY KEY,
    application_type VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    site VARCHAR(100),
    city VARCHAR(100),
    office VARCHAR(100),
    delivery_site VARCHAR(100),
    appointment_date VARCHAR(50),
    appointment_time VARCHAR(50),
    firstname VARCHAR(100),
    middlename VARCHAR(100),
    lastname VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    gender VARCHAR(10),
    dob VARCHAR(10),
    under18 VARCHAR(5),
    birthplace VARCHAR(100),
    adopted VARCHAR(5),
    birth_certificate VARCHAR(5),
    nationality VARCHAR(50),
    marital_status VARCHAR(50),
    occupation VARCHAR(50),
    region VARCHAR(100),
    address_city VARCHAR(100),
    subcity VARCHAR(100),
    woreda VARCHAR(50),
    kebele VARCHAR(50),
    house_no VARCHAR(50),
    id_no VARCHAR(50),
    mother_first_name VARCHAR(50) NOT NULL,
    mother_father_name VARCHAR(50) NOT NULL,
    mother_grandfather_name VARCHAR(50) NOT NULL,
    father_first_name VARCHAR(50) NOT NULL,
    father_father_name VARCHAR(50) NOT NULL,
    father_grandfather_name VARCHAR(50) NOT NULL,
    spouse_first_name VARCHAR(50),
    spouse_father_name VARCHAR(50),
    spouse_grandfather_name VARCHAR(50),
    -- Passport Information
    old_passport_number VARCHAR(50),
    old_issue_date VARCHAR(50),
    old_expiry_date VARCHAR(50),
    correction_type VARCHAR(50),
     
   -- Attachments
    old_passport_attachment VARCHAR(255),
    photo_attachment VARCHAR(255),
    id_front_attachment VARCHAR(255),
    id_back_attachment VARCHAR(255),

    pageNo VARCHAR(6),
    application_no VARCHAR(100),
    registered_date VARCHAR(50),  
    -- System Fields
    application_status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE Table Renewal_Application(
    id INT AUTO_INCREMENT PRIMARY KEY,
    application_type VARCHAR(50) NOT NULL,
    category VARCHAR(50),
    
    service_type VARCHAR(50) NOT NULL,

    site VARCHAR(100),
    city VARCHAR(100),
    office VARCHAR(100),
    delivery_site VARCHAR(100),
    appointment_date VARCHAR(50),
    appointment_time VARCHAR(50),
    firstname VARCHAR(100),
    middlename VARCHAR(100),
    lastname VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    gender VARCHAR(10),
    dob VARCHAR(10),
    under18 VARCHAR(5),
    birthplace VARCHAR(100),
    adopted VARCHAR(5),
    birth_certificate VARCHAR(5),
    nationality VARCHAR(50),
    marital_status VARCHAR(50),
    occupation VARCHAR(50),
    region VARCHAR(100),
    address_city VARCHAR(100),
    subcity VARCHAR(100),
    woreda VARCHAR(50),
    kebele VARCHAR(50),
    house_no VARCHAR(50),
    id_no VARCHAR(50),
    mother_first_name VARCHAR(50) NOT NULL,
    mother_father_name VARCHAR(50) NOT NULL,
    mother_grandfather_name VARCHAR(50) NOT NULL,
    father_first_name VARCHAR(50) NOT NULL,
    father_father_name VARCHAR(50) NOT NULL,
    father_grandfather_name VARCHAR(50) NOT NULL,
    spouse_first_name VARCHAR(50),
    spouse_father_name VARCHAR(50),
    spouse_grandfather_name VARCHAR(50),
     -- Passport Information
    old_passport_number VARCHAR(50),
    old_issue_date VARCHAR(50),
    old_expiry_date VARCHAR(50),
    has_correction BOOLEAN DEFAULT FALSE,
    correction_type VARCHAR(100),
        
   -- Attachments
    old_passport_attachment VARCHAR(255),
    photo_attachment VARCHAR(255),
    id_front_attachment VARCHAR(255),
    id_back_attachment VARCHAR(255),

    pageNo VARCHAR(6),
    application_no VARCHAR(100),
    registered_date VARCHAR(50),  
    -- System Fields
    application_status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);