CREATE TABLE applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50),
    category VARCHAR(50),
    site VARCHAR(100),
    city VARCHAR(100),
    office VARCHAR(100),
    delivery VARCHAR(100),
    appointment_date VARCHAR(50),
    appointment_time VARCHAR(50),
    firstname VARCHAR(100),
    middlename VARCHAR(100),
    lastname VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(100),
    gender VARCHAR(10),
    dob DATE,
    under18 VARCHAR(5),
    birthplace VARCHAR(100),
    adopted VARCHAR(5),
    birth_certificate VARCHAR(5),
    nationality VARCHAR(50),
    marital_status VARCHAR(50),
    occupation VARCHAR(50),
    region VARCHAR(100),
    address_city VARCHAR(100),
    subcity VARCHAR(100),
    woreda VARCHAR(50),
    kebele VARCHAR(50),
    house_no VARCHAR(50),
    id_no VARCHAR(50),
    mother VARCHAR(100),
    father VARCHAR(100),
    spouse VARCHAR(100),
    birth_certificate_front VARCHAR(255),
    birth_certificate_back VARCHAR(255),
    id_front VARCHAR(255),
    id_back VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
